// Getting the images of the closed doors by their IDs in the html file

const doorImage1 = document.getElementById('door1')
const doorImage2 = document.getElementById('door2')
const doorImage3 = document.getElementById('door3')
const startButton = document.getElementById('start')
let currentlyPlaying = true

// Assigning the links to open door images to variables

const botDoorPath = 'https://s3.amazonaws.com/codecademy-content/projects/chore-door/images/robot.svg'

const beachDoorPath = 'https://s3.amazonaws.com/codecademy-content/projects/chore-door/images/beach.svg'

const spaceDoorPath = 'https://s3.amazonaws.com/codecademy-content/projects/chore-door/images/space.svg'

const closedDoorPath = 'https://s3.amazonaws.com/codecademy-content/projects/chore-door/images/closed_door.svg'

let numClosedDoors = 3
let openDoor1
let openDoor2
let openDoor3

const isBot = door => door.src === botDoorPath

// Checks if the door has already been clicked

const isClicked = door => door.src !== closedDoorPath

// Decreases the number of closed doors. Calls game over if all doors are open.

const playDoor = (door) => {
  if (numClosedDoors === 0) {
    gameOver('win')
  } else if (isBot(door)) {
    gameOver()
  }
}

// Sets the robot behind a door based on a random number generated by the number of doors. Sets the other images behind the remaining doors.

const randomChoreDoorGenerator = () => {
  const choreDoor = Math.floor(Math.random() * numClosedDoors)
  if (choreDoor === 0) {
    openDoor1 = botDoorPath
    openDoor2 = beachDoorPath
    openDoor3 = spaceDoorPath
  } else if (choreDoor === 1) {
    openDoor2 = botDoorPath
    openDoor1 = beachDoorPath
    openDoor3 = spaceDoorPath
  } else {
    openDoor3 = botDoorPath
    openDoor1 = beachDoorPath
    openDoor2 = spaceDoorPath
  }
}

// Functions to change the image from closed door to open door on click

doorImage1.onclick = () => {
  if (!isClicked(doorImage1) && currentlyPlaying) {
    doorImage1.src = openDoor1
    playDoor(doorImage1)
  }
}

doorImage2.onclick = () => {
  if (!isClicked(doorImage2) && currentlyPlaying) {
    doorImage2.src = openDoor2
    playDoor(doorImage2)
  }
}

doorImage3.onclick = (door) => {
  if (!isClicked(doorImage3) && currentlyPlaying) {
    doorImage3.src = openDoor3
    playDoor(doorImage3)
  }
}

// Start a new game if the button is clicked. Starting a new game resets all the doors to closed.

startButton.onclick = () => {
  if (!currentlyPlaying) {
    startRound()
  }
}

const startRound = () => {
  doorImage1.src = closedDoorPath
  doorImage2.src = closedDoorPath
  doorImage3.src = closedDoorPath
  numClosedDoors = 3
  startButton.innerHTML = 'Good luck!'
  currentlyPlaying = true
  randomChoreDoorGenerator()
}

// Game over when player wins or all doors opened

const gameOver = (status) => {
  if (status === 'win') {
    startButton.innerHTML = 'You win! Play again?'
  } else {
    startButton.innerHTML = 'Game Over! Play again?'
  }
  currentlyPlaying = false
}

startRound()
